// views/Help.jsx
import { React } from "../deps.ts";

class HelpPage extends React.Component {
  render() {
    return (
      <div>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <link rel="icon" href="/public/img/ico.png" />
        <title>Odontoradiosis | Ajuda</title>
        <link rel="stylesheet" type="text/css" href="/public/css/app.css" />
        <link
          rel="stylesheet"
          href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
        />
        {/* Google Font: Source Sans Pro */}
        <link
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
          rel="stylesheet"
        />
        {/* Main System CSS */}
        <link rel="stylesheet" type="text/css" href="/public/css/bezier.css" />
        <div className="wrapper">
          {/* Navbar */}
          <nav className="main-header navbar navbar-expand bg-white navbar-light border-bottom">
            <ul className="navbar-nav">
              <li className="nav-item d-none d-sm-inline-block">
                <a href="/" className="nav-link">
                  Home
                </a>
              </li>
              <li className="nav-item d-none d-sm-inline-block">
                <a href="/help" className="nav-link">
                  Ajuda
                </a>
              </li>
            </ul>
          </nav>
          {/* /.navbar */}
          {/* Main Sidebar Container */}
          <aside className="main-sidebar sidebar-dark-primary elevation-4">
            {/* Brand Logo */}
            <a align="middle" href="/" className="brand-link">
              <img
                width={200}
                height={133}
                src="/public/img/odontoradiosis_logo.png"
                alt="Odontoradiosis"
                align="middle"
              />
            </a>
            {/* Sidebar */}
            <div className="sidebar">
              {/* Sidebar Menu */}
              <nav className="mt-2">
                <ul
                  className="nav nav-pills nav-sidebar flex-column"
                  data-widget="treeview"
                  role="menu"
                  data-accordion="false"
                >
                  <div align="center">
                    <li className="nav-item">
                      <a className="nav-link js-scroll-trigger" href="#about">
                        <b>SOBRE</b>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        className="nav-link js-scroll-trigger"
                        href="#experience"
                      >
                        <b>RADIOGRAFIAS</b>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        className="nav-link js-scroll-trigger"
                        href="#education"
                      >
                        <b>EFEITOS</b>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link js-scroll-trigger" href="#skills">
                        <b>DESENHO ANATÔMICO</b>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a
                        className="nav-link js-scroll-trigger"
                        href="#interests"
                      >
                        <b>PONTOS</b>
                      </a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link js-scroll-trigger" href="#awards">
                        <b>EDIÇÃO</b>
                      </a>
                    </li>
                  </div>
                </ul>
              </nav>
              {/* /.sidebar-menu */}
            </div>
            {/* /.sidebar */}
          </aside>
          {/* Content Wrapper. Contains page content */}
          <div className="content-wrapper">
            {/* Content Header (Page header) */}
            <div className="content-header">
              <div className="container-fluid">
                <div className="row mb-2">
                  <div className="col-sm-6"></div>
                  {/* /.col */}
                  <div className="col-sm-6"></div>
                  {/* /.col */}
                </div>
                {/* /.row */}
              </div>
              {/* /.container-fluid */}
            </div>
            {/* /.content-header */}
            <div className="container-fluid p-0">
              <section
                className="resume-section p-3 p-lg-5 d-flex align-items-center"
                id="about"
              >
                <div className="w-100">
                  <h1 className="mb-0">
                    <b>ODONTO</b>
                    <span className="text-primary">
                      <b>RADIOSIS</b>
                    </span>
                  </h1>
                  <div className="subheading mb-5">
                    Abel Ramalho Galvão¹ · João Victor Oliveira Couto² ·
                    <a href="mailto:abel.ramalho18@gmail.com">
                      abel.ramalho18@gmail.com¹
                    </a>{" "}
                    ·{" "}
                    <a href="mailto:jictyvoo.ecomp@gmail.com">
                      jictyvoo.ecomp@gmail.com²
                    </a>
                  </div>
                  <p className="lead mb-5" />
                  <p align="justify">
                    A cefalometria radiográfica consiste nas mensurações da
                    radiografia cefalométrica lateral e é fundamental para o
                    estudo da forma e do crescimento do crânio. As aplicações da
                    cefalometria na Ortodontia possibilita a visualização dos
                    chamados pontos de referência, faciais e cranianos.
                  </p>
                  <br />
                  <p align="justify">
                    A partir das radiografias cefalométricas laterais, os
                    diagnósticos são realizados mediante aos traçados
                    cefalométricos ou analisando a localização do conjunto de
                    pontos cefalométricos que, uma vez unidos, permitem a
                    realização das mensurações (ângulos e distâncias) ditadas
                    pelas diferentes análises cefalométricas existentes.
                  </p>
                  <br />
                  <p align="justify">
                    Por muitos anos, a análise cefalométrica foi realizada
                    manualmente, dificultando a reprodução dos traçados quando
                    comparado por diversos observadores. Com o objetivo de
                    auxiliar os especialistas da área de radiologia
                    odontológica, uma ferramenta intitulada ODONTORADIOSIS vem
                    sendo desenvolvida na Universidade Estadual de Feira de
                    Santana.
                  </p>
                  <br />
                  <p />
                  <div className="social-icons">
                    <a href="https://github.com/argalvao">
                      <i className="fab fa-github" />
                    </a>
                    <a href="https://www.facebook.com/abel.galvao.58">
                      <i className="fab fa-facebook-f" />
                    </a>
                    <a href="https://github.com/Jictyvoo/">
                      <i className="fab fa-github" />
                    </a>
                    <a href="https://www.facebook.com/Jictyvoo">
                      <i className="fab fa-facebook-f" />
                    </a>
                  </div>
                </div>
              </section>
              <hr className="m-0" />
              <section
                className="resume-section p-3 p-lg-5 d-flex justify-content-center"
                id="experience"
              >
                <div className="w-100">
                  <h2 className="mb-5">
                    <b>RADIOGRAFIAS</b>
                  </h2>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Abrir radiografia</h3>
                      <p align="justify">
                        Para abrir uma radiografia, basta clicar no menu lateral
                        direito localizado no canto superior direita da
                        ferramenta Odontoradiosis e clicar no botão "Abrir
                        radiografia".
                      </p>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/abrir_radiografia.png"
                      alt=""
                    />
                  </div>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Selecionar radiografia</h3>
                      <p align="justify">
                        Para selecionar uma radiografia a ser utilizada, basta
                        clicar sobre uma radiografia exibida na janela de
                        seleção.
                      </p>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/selecionar_radiografia.png"
                      alt=""
                    />
                  </div>
                </div>
              </section>
              <hr className="m-0" />
              <section
                className="resume-section p-3 p-lg-5 d-flex align-items-center"
                id="education"
              >
                <div className="w-100">
                  <h2 className="mb-5">
                    <b>EFEITOS</b>
                  </h2>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Aplicação de efeitos</h3>
                      <div align="justify">
                        Podem ser aplicados até 4 tipos de efeitos com o
                        objetivo de melhorar a imagem para a marcação dos pontos
                        cefalométricos com maior precisão. Sendo eles:
                        Contraste; Brilho, Nagativo e Escala de Cinzas. Para
                        realizar a aplicação dos efeitos, basta definir a
                        intesidade dos mesmos nas barras de efeitos localizadas
                        no menu lateral esquerdo. Para reverter a aplicação dos
                        efeitos, basta clicar no botão "Desfazer", também
                        localizado no menu lateral esquerdo.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/efeitos.png"
                      alt=""
                    />
                  </div>
                </div>
              </section>
              <hr className="m-0" />
              <section
                className="resume-section p-3 p-lg-5 d-flex align-items-center"
                id="skills"
              >
                <div className="w-100">
                  <h2 className="mb-5">
                    <b>DESENHO ANATÔMICO</b>
                  </h2>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Seleção da curva</h3>
                      <div align="justify">
                        Para escolher qual curva irá ajustar, basta clicar no
                        select de curvas localizado no menu lateral esquerdo.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/menu_curvas.png"
                      alt=""
                    />
                  </div>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Ajuste do Desenho Anatômico</h3>
                      <div align="justify">
                        Após selecionar a curva que deseja ajustar, basta clicar
                        e arrastar nos pontos de controle para mudar o tamanho e
                        ajustar sobre a radografia.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/ajuste_curvas.png"
                      alt=""
                    />
                  </div>
                </div>
              </section>
              <hr className="m-0" />
              <section
                className="resume-section p-3 p-lg-5 d-flex align-items-center"
                id="interests"
              >
                <div className="w-100">
                  <h2 className="mb-5">
                    <b>PONTOS</b>
                  </h2>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Seleção de pontos</h3>
                      <div align="justify">
                        Para escolher qual ponto cefalométrico irá marcar, basta
                        clicar no select de pontos localizado no menu lateral
                        esquerdo.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/menu_pontos.png"
                      alt=""
                    />
                  </div>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">
                        Marcação de Pontos cefalométricos
                      </h3>
                      <div align="justify">
                        Após selecionar o ponto cefalométrico que deseja marcar
                        sobre a radiografia, basta clicar clicar sobre a mesma
                        para que o ponto seja marcado. No canto superior
                        direito, uma imagem de referência irá auxiliar na
                        localização do ponto a ser marcado.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/marcar_ponto.png"
                      alt=""
                    />
                  </div>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Salvar</h3>
                      <div align="justify">
                        Após realizar todos os procedimentos desejados, para
                        salvar, basta clicar no menu lateral esquerdo e clicar
                        no botão "Salvar".
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/salvar_marcacao.png"
                      alt=""
                    />
                  </div>
                </div>
              </section>
              <hr className="m-0" />
              <section
                className="resume-section p-3 p-lg-5 d-flex align-items-center"
                id="awards"
              >
                <div className="w-100">
                  <h2 className="mb-5">
                    <b>EDIÇÃO</b>
                  </h2>
                  <div className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div className="resume-content">
                      <h3 className="mb-0">Editar radiografias salvas</h3>
                      <div align="justify">
                        Para uma radiografia salva, basta clicar no menu lateral
                        esquerdo e clicar no botão "Editar radiografia". Uma
                        janela com as radiografias salvas será exibida no qual
                        poderá ser selecionada a radiografia a ser editada.
                      </div>
                    </div>
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/menu_edicao.png"
                      alt=""
                    />
                  </div>
                  <div className="resume-content">
                    <img
                      className="img-fluid img-profile mx-auto mb-2"
                      src="/public/img/tutorial/editar_radiografia.png"
                      alt=""
                    />
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default HelpPage;

// src/views/Help.vue
<template>
  <div>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta httpEquiv="x-ua-compatible" content="ie=edge" />
    <link rel="icon" href="/public/img/ico.png" />
    <title>Odontoradiosis | Ajuda</title>
    <link rel="stylesheet" type="text/css" href="/public/css/app.css" />
    <link
      rel="stylesheet"
      href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    />
    <!--Google Font: Source Sans Pro-->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
      rel="stylesheet"
    />
    <!--Main System CSS-->
    <link rel="stylesheet" type="text/css" href="/public/css/bezier.css" />
    <div className="wrapper">
      <!--Navbar-->
      <nav
        className="main-header navbar navbar-expand bg-white navbar-light border-bottom"
      >
        <ul className="navbar-nav">
          <li className="nav-item d-none d-sm-inline-block">
            <a href="/" className="nav-link"> Home </a>
          </li>
          <li className="nav-item d-none d-sm-inline-block">
            <a href="/help" className="nav-link"> Ajuda </a>
          </li>
        </ul>
      </nav>
      <!--/.navbar-->
      <!--Main Sidebar Container-->
      <aside className="main-sidebar sidebar-dark-primary elevation-4">
        <!--Brand Logo-->
        <a align="middle" href="/" className="brand-link">
          <img
            width="{200}"
            height="{133}"
            src="/public/img/odontoradiosis_logo.png"
            alt="Odontoradiosis"
            align="middle"
          />
        </a>
        <!--Sidebar-->
        <div className="sidebar">
          <!--Sidebar Menu-->
          <nav className="mt-2">
            <ul
              className="nav nav-pills nav-sidebar flex-column"
              data-widget="treeview"
              role="menu"
              data-accordion="false"
            >
              <div align="center">
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#about">
                    <b>SOBRE</b>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#experience">
                    <b>RADIOGRAFIAS</b>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#education">
                    <b>EFEITOS</b>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#skills">
                    <b>DESENHO ANATÔMICO</b>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#interests">
                    <b>PONTOS</b>
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link js-scroll-trigger" href="#awards">
                    <b>EDIÇÃO</b>
                  </a>
                </li>
              </div>
            </ul>
          </nav>
          <!--/.sidebar-menu-->
        </div>
        <!--/.sidebar-->
      </aside>
      <!--Content Wrapper. Contains page content-->
      <div className="content-wrapper">
        <!--Content Header (Page header)-->
        <div className="content-header">
          <div className="container-fluid">
            <div className="row mb-2">
              <div className="col-sm-6"></div>
              <!--/.col-->
              <div className="col-sm-6"></div>
              <!--/.col-->
            </div>
            <!--/.row-->
          </div>
          <!--/.container-fluid-->
        </div>
        <!--/.content-header-->
        <div className="container-fluid p-0">
          <section
            className="resume-section p-3 p-lg-5 d-flex align-items-center"
            id="about"
          >
            <div className="w-100">
              <h1 className="mb-0">
                <b>ODONTO</b>
                <span className="text-primary">
                  <b>RADIOSIS</b>
                </span>
              </h1>
              <div className="subheading mb-5">
                Abel Ramalho Galvão¹ · João Victor Oliveira Couto² ·
                <a href="mailto:abel.ramalho18@gmail.com">
                  abel.ramalho18@gmail.com¹ </a
                >{" "} ·{" "}
                <a href="mailto:jictyvoo.ecomp@gmail.com">
                  jictyvoo.ecomp@gmail.com²
                </a>
              </div>
              <p className="lead mb-5" />
              <p align="justify">
                A cefalometria radiográfica consiste nas mensurações da
                radiografia cefalométrica lateral e é fundamental para o estudo
                da forma e do crescimento do crânio. As aplicações da
                cefalometria na Ortodontia possibilita a visualização dos
                chamados pontos de referência, faciais e cranianos.
              </p>
              <br />
              <p align="justify">
                A partir das radiografias cefalométricas laterais, os
                diagnósticos são realizados mediante aos traçados cefalométricos
                ou analisando a localização do conjunto de pontos cefalométricos
                que, uma vez unidos, permitem a realização das mensurações
                (ângulos e distâncias) ditadas pelas diferentes análises
                cefalométricas existentes.
              </p>
              <br />
              <p align="justify">
                Por muitos anos, a análise cefalométrica foi realizada
                manualmente, dificultando a reprodução dos traçados quando
                comparado por diversos observadores. Com o objetivo de auxiliar
                os especialistas da área de radiologia odontológica, uma
                ferramenta intitulada ODONTORADIOSIS vem sendo desenvolvida na
                Universidade Estadual de Feira de Santana.
              </p>
              <br />
              <p />
              <div className="social-icons">
                <a href="https://github.com/argalvao">
                  <i className="fab fa-github" />
                </a>
                <a href="https://www.facebook.com/abel.galvao.58">
                  <i className="fab fa-facebook-f" />
                </a>
                <a href="https://github.com/Jictyvoo/">
                  <i className="fab fa-github" />
                </a>
                <a href="https://www.facebook.com/Jictyvoo">
                  <i className="fab fa-facebook-f" />
                </a>
              </div>
            </div>
          </section>
          <hr className="m-0" />
          <section
            className="resume-section p-3 p-lg-5 d-flex justify-content-center"
            id="experience"
          >
            <div className="w-100">
              <h2 className="mb-5">
                <b>RADIOGRAFIAS</b>
              </h2>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Abrir radiografia</h3>
                  <p align="justify">
                    Para abrir uma radiografia, basta clicar no menu lateral
                    direito localizado no canto superior direita da ferramenta
                    Odontoradiosis e clicar no botão "Abrir radiografia".
                  </p>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/abrir_radiografia.png"
                  alt=""
                />
              </div>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Selecionar radiografia</h3>
                  <p align="justify">
                    Para selecionar uma radiografia a ser utilizada, basta
                    clicar sobre uma radiografia exibida na janela de seleção.
                  </p>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/selecionar_radiografia.png"
                  alt=""
                />
              </div>
            </div>
          </section>
          <hr className="m-0" />
          <section
            className="resume-section p-3 p-lg-5 d-flex align-items-center"
            id="education"
          >
            <div className="w-100">
              <h2 className="mb-5">
                <b>EFEITOS</b>
              </h2>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Aplicação de efeitos</h3>
                  <div align="justify">
                    Podem ser aplicados até 4 tipos de efeitos com o objetivo de
                    melhorar a imagem para a marcação dos pontos cefalométricos
                    com maior precisão. Sendo eles: Contraste; Brilho, Nagativo
                    e Escala de Cinzas. Para realizar a aplicação dos efeitos,
                    basta definir a intesidade dos mesmos nas barras de efeitos
                    localizadas no menu lateral esquerdo. Para reverter a
                    aplicação dos efeitos, basta clicar no botão "Desfazer",
                    também localizado no menu lateral esquerdo.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/efeitos.png"
                  alt=""
                />
              </div>
            </div>
          </section>
          <hr className="m-0" />
          <section
            className="resume-section p-3 p-lg-5 d-flex align-items-center"
            id="skills"
          >
            <div className="w-100">
              <h2 className="mb-5">
                <b>DESENHO ANATÔMICO</b>
              </h2>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Seleção da curva</h3>
                  <div align="justify">
                    Para escolher qual curva irá ajustar, basta clicar no select
                    de curvas localizado no menu lateral esquerdo.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/menu_curvas.png"
                  alt=""
                />
              </div>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Ajuste do Desenho Anatômico</h3>
                  <div align="justify">
                    Após selecionar a curva que deseja ajustar, basta clicar e
                    arrastar nos pontos de controle para mudar o tamanho e
                    ajustar sobre a radografia.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/ajuste_curvas.png"
                  alt=""
                />
              </div>
            </div>
          </section>
          <hr className="m-0" />
          <section
            className="resume-section p-3 p-lg-5 d-flex align-items-center"
            id="interests"
          >
            <div className="w-100">
              <h2 className="mb-5">
                <b>PONTOS</b>
              </h2>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Seleção de pontos</h3>
                  <div align="justify">
                    Para escolher qual ponto cefalométrico irá marcar, basta
                    clicar no select de pontos localizado no menu lateral
                    esquerdo.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/menu_pontos.png"
                  alt=""
                />
              </div>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Marcação de Pontos cefalométricos</h3>
                  <div align="justify">
                    Após selecionar o ponto cefalométrico que deseja marcar
                    sobre a radiografia, basta clicar clicar sobre a mesma para
                    que o ponto seja marcado. No canto superior direito, uma
                    imagem de referência irá auxiliar na localização do ponto a
                    ser marcado.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/marcar_ponto.png"
                  alt=""
                />
              </div>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Salvar</h3>
                  <div align="justify">
                    Após realizar todos os procedimentos desejados, para salvar,
                    basta clicar no menu lateral esquerdo e clicar no botão
                    "Salvar".
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/salvar_marcacao.png"
                  alt=""
                />
              </div>
            </div>
          </section>
          <hr className="m-0" />
          <section
            className="resume-section p-3 p-lg-5 d-flex align-items-center"
            id="awards"
          >
            <div className="w-100">
              <h2 className="mb-5">
                <b>EDIÇÃO</b>
              </h2>
              <div
                className="resume-item d-flex flex-column flex-md-row justify-content-between mb-5"
              >
                <div className="resume-content">
                  <h3 className="mb-0">Editar radiografias salvas</h3>
                  <div align="justify">
                    Para uma radiografia salva, basta clicar no menu lateral
                    esquerdo e clicar no botão "Editar radiografia". Uma janela
                    com as radiografias salvas será exibida no qual poderá ser
                    selecionada a radiografia a ser editada.
                  </div>
                </div>
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/menu_edicao.png"
                  alt=""
                />
              </div>
              <div className="resume-content">
                <img
                  className="img-fluid img-profile mx-auto mb-2"
                  src="/public/img/tutorial/editar_radiografia.png"
                  alt=""
                />
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>
